[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]
# Eslatma: npm ci install phase'da allaqachon ishlatilgan, shuning uchun bu yerda kerak emas

[start]
cmd = "npx serve -s dist -l ${PORT:-3000}"

[staticAssets]
"dist" = "/"

